config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */
use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;
use Cake\Core\Configure;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

/**** Users functions ****/
$routes->connect('/users/login', ['controller' => 'Users', 'action' => 'login']);
$routes->connect('/users/register', ['controller' => 'Users', 'action' => 'register']);
$routes->connect('/users/register-detail-corp', ['controller' => 'Users', 'action' => 'registerDetailCorp']);
$routes->connect('/users/register-detail-bank', ['controller' => 'Users', 'action' => 'registerDetailBank']);
$routes->connect('/users/bank-auto-comp', ['controller' => 'Users', 'action' => 'bankAutoComp']);
$routes->connect('/users/confirm-detail', ['controller' => 'Users', 'action' => 'confirmDetail']);
$routes->connect('/users/complete-detail', ['controller' => 'Users', 'action' => 'completeDetail']);
$routes->connect('/users/request-reset-password', ['controller' => 'Users', 'action' => 'requestResetPassword']);
$routes->connect('/users/validate-email/*', ['controller' => 'Users', 'action' => 'validateEmail']);
$routes->connect('/users/reset-password/*', ['controller' => 'Users', 'action' => 'resetPassword']);
$routes->connect('/users/change-password/*', ['controller' => 'Users', 'action' => 'changePassword']);
$routes->connect('/users/logout', ['controller' => 'Users', 'action' => 'logout']);
$routes->connect('/users/profile', ['controller' => 'Users', 'action' => 'profile']);
$routes->connect('/users/edit/*', ['controller' => 'Users', 'action' => 'edit']);
$routes->connect('/users/delete/*', ['controller' => 'Users', 'action' => 'delete']);
$routes->connect('/users/change-email', ['controller' => 'Users', 'action' => 'changeEmail']);
$routes->connect('/users/confirm-email/*', ['controller' => 'Users', 'action' => 'confirmEmail']);
$routes->connect('/users/complete-change-email', ['controller' => 'Users', 'action' => 'completeChangeEmail']);
/**** Corp functions ****/
$routes->connect('/corp/create-loan-item', ['controller' => 'Corp', 'action' => 'createLoanItem']);
$routes->connect('/corp/get-subcategory-list', ['controller' => 'Corp', 'action' => 'getSubcategoryList']);
$routes->connect('/corp/view-loan-item', ['controller' => 'Corp', 'action' => 'viewLoanItem']);
$routes->connect('/corp/visible-status-change', ['controller' => 'Corp', 'action' => 'visibleStatusChange']);
$routes->connect('/corp/delete-loan-item', ['controller' => 'Corp', 'action' => 'deleteLoanItem']);
$routes->connect('/corp/delete-finance-item', ['controller' => 'Corp', 'action' => 'deleteFinanceInfo']);
$routes->connect('/corp/update-loan-item', ['controller' => 'Corp', 'action' => 'updateLoanItem']);
$routes->connect('/corp/update-finance-item', ['controller' => 'Corp', 'action' => 'updateFinanceItem']);
$routes->connect('/corp/view-block/*', ['controller' => 'Corp', 'action' => 'viewBlock']);
$routes->connect('/corp/get-bank-list-by-search', ['controller' => 'Corp', 'action' => 'getBankListBySearch']);
$routes->connect('/corp/file-download/*', ['controller' => 'Corp', 'action' => 'fileDownload']);
$routes->connect('/corp/file-delete/*', ['controller' => 'Corp', 'action' => 'fileDelete']);
$routes->connect('/corp/upload-loan-image', ['controller' => 'Corp', 'action' => 'uploadLoanImage']);
$routes->connect('/corp/delete-loan-image/*', ['controller' => 'Corp', 'action' => 'deleteLoanImage']);
/**** Bank functions ****/
$routes->connect('/bank/view-detail', ['controller' => 'Bank', 'action' => 'viewDetail']);
$routes->connect('/bank/search', ['controller' => 'Bank', 'action' => 'search']);
$routes->connect('/bank/favorite-action', ['controller' => 'Bank', 'action' => 'favoriteAction']);

//temp
$routes->connect('/corp/stripe-func', ['controller' => 'Corp', 'action' => 'stripeFunc']);

Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */

    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

src/Model/Entity/Bank.php
<?php

namespace App\Model\Entity;

use Cake\ORM\Entity;

class Bank extends Entity
{
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/BanksTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class BanksTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('banks');
        $this->setPrimaryKey('id');
        $this->hasMany('Blocklists');
        $this->hasMany('users');
    }

}

src/Model/Table/LoanTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Table;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\Validation\Validator;

class LoanTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('corp_loan');
        $this->setPrimaryKey('id');
        $this->addBehavior('Timestamp');
        $this->belongsTo('Categories');
        $this->belongsTo('SubCategories');
        $this->belongsTo('users');
        $this->hasMany('BankFavorites');

        // added for search
        $this->addBehavior('Search.Search');
        $this->searchManager()
        ->add('search', 'Search.Like', [
            'before' => true,
            'after' => true,
            'mode' => 'or',
            'comparison' => 'LIKE',
            'wildcardAny' => '*',
            'wildcardOne' => '?',
            'multiValue' => true,
            'multiValueSeparator' => '　',
            // 検索カラム名
            'field' => ['loan_title', 'job_description', 'loan_purpose', 'prospect']
          ]);
    }

    public function validationDefault(Validator $validator)
    {
        $validator = parent::validationDefault($validator);

        $validator
            ->maxLength('loan_title', 50, __('50文字以内で入力してください。'));

        $validator
            ->maxLength('job_description', 800, __('800文字以内で入力してください。'));

        $validator
            ->numeric('desired_loan_amount', __('0以上の数値を入力してください。'))
            ->maxLength('desired_loan_amount', 12, __('12桁以下の値を入力してください。'));

        $validator
            ->maxLength('loan_purpose_detail', 20, __('20文字以内で入力してください。'));

        $validator
            ->maxLength('loan_purpose', 800, __('800文字以内で入力してください。'));

        $validator
            ->maxLength('prospect', 800, __('800文字以内で入力してください。'))
            ->allowEmpty('prospect');

        $validator
            ->notEmpty('loan_purpose');

        $validator
            ->notEmpty('loan_purpose_detail', '資金使途を記載してください。', function ($context) {
                return ($context['data']['loan_purpose'] == '2');
            })
            ->maxLength('loan_purpose_detail', 20, __('20桁以下の値を入力してください。'));

        return $validator;
    }

    public function validationDraft(Validator $validator)
    {
        $validator
            ->numeric('desired_loan_amount', __('0以上の数値を入力してください。'))
            ->maxLength('desired_loan_amount', 12, __('12桁以下の値を入力してください。'))
            ->allowEmpty('desired_loan_amount');

        $validator
            ->numeric('loan_period', __('0以上の数値を入力してください。'))
            ->maxLength('loan_period', 3, __('3桁以下の値を入力してください。'))
            ->allowEmpty('loan_period');

        $validator
            ->maxLength('loan_purpose', 800, __('800文字以内で入力してください。'))
            ->allowEmpty('loan_purpose');

        $validator
            ->maxLength('prospect', 800, __('800文字以内で入力してください。'))
            ->allowEmpty('prospect');

        return $validator;
    }

}

src/Controller/BankController.php
<?php

namespace App\Controller;

use App\Controller\Traits\TableAccessTrait;
use App\Controller\Traits\UserLoggingsTrait;
use App\Controller\Traits\ViewLoanItemTrait;
use App\Controller\Traits\LoginTrait;
use App\Controller\Traits\CommonFuncTrait;
use App\Controller\Traits\FavoritesTrait;
use Cake\Core\Configure;
use Cake\Controller\Controller;
use Cake\Event\Event;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use Cake\Routing\Router;

/**
 * Customaized Controller for Bank account users
 */

class BankController extends AppController
{
    use CommonFuncTrait;
    use ViewLoanItemTrait;
    use UserLoggingsTrait;
    use LoginTrait;
    use FavoritesTrait;

    public $paginate = [
        'limit' => 25,
        ];

    public function initialize()
    {
        parent::initialize();

        $this->loadModel('Users');
        $this->loadModel('Loan');
        $this->loadModel('Banks');
        $this->loadModel('Blocklists');
        $this->loadModel('Finance');
        $this->loadModel('Categories');
        $this->loadModel('SubCategories');
        $this->loadModel('UserLoggings');
        $this->loadModel('BankFavorites');
        $this->loadComponent('Paginator');

        // add friendsofcake/search
        $this->loadComponent('Search.Prg', [
            'actions' => ['home']
        ]);
    }

    public function beforeFilter(Event $event) {
        parent::beforeFilter($event);

        //multi-logging check
        $this->loggingCheck();

        // create random number
        if ($this->request->getSession()->read('seed') == '') {
            $this->request->getSession()->write('seed', mt_rand());
        }

        $userId = $this->Auth->user('id');
        if (!isset($userId)) {
            return $this->redirect(['controller' => 'users', 'action' => 'login']);
        }

        $user = $this->Users->get($userId);
        if (empty($user['phone'])) {
            return $this->redirect(['controller' => 'Users', 'action' => 'registerDetailBank']);
        }
    }

    public function home()
    {
        try {
            $loginId = $this->Auth->user('id');
            $user = $this->Users->find()->where(['users.id' => $loginId])->contain(['banks'])->first();
            $this->itemSearchConditions();

            $favs = $this->BankFavorites->find()->where(['user_id' => $user->id])->toArray();
            foreach ($favs as $fav) {
                $fav_items[] = $this->Loan->find()->where(['id' => $fav->loan_id])->first();
            }

            $this->set('user', $user);
            $this->set('fav_items', $fav_items);
            $this->render();
            return ;

        } catch (MissingTemplateException $exception) {
            if (Configure::read('debug')) {
                throw $exception;
            }
            throw new NotFoundException();
        }
    }

    /**
     * Common function for limitting the returning value
     * getting minimum range or maximum value
     *
     * @param entity $query
     * @param column_name $target
     * @param numeric $min
     * @param numeric $max
     * @return entity $query
     */
    public function returnValueByRange($query, $target, $min, $max)
    {
        if ($min && !$max) {
            $query = $query->where(function ($exp) use ($target, $min) {
                return $exp->gte($target, $min);
              });
        } else if (!$min && $max) {
            $query = $query->where(function ($exp) use ($target, $max) {
                return $exp->lte($target, $max);
              });
        } else {
            $query = $query->where(function ($exp) use ($target, $min, $max) {
                return $exp->between($target, $min, $max);
            });
        }
        return $query;
    }
}

src/Template/Bank/view_detail.ctp
<?php

$loan = $entities['loan'];
$finance = $entities['finance'];

echo $this->Html->css('/scss/bank/view-detail.min.css');
echo '<script type="text/javascript">var var_loan_id = '.json_encode($loan->id).';</script>';
echo $this->Html->script('/js/bank/view_detail.min.js', ['block' => true]);

?>

<div class="contents-wrapper container view-detail">

    <div class="user-info">
        <div class="contents-semi-label">
            <?= __('会社情報') ?>
        </div>
        <div class="contents">
            <table>
                <tr class="row mx-0">
                    <th class="col-3"><?= __('会社名') ?></th>
                    <td class="col-9"><?= h($loan->user->company_name) ?></td>
                </tr>
                <tr class="row mx-0">
                    <th class="col-3"><?= __('URL') ?></th>
                    <td class="col-9"><a href=<?= $loan->user->url ?> target="_blank"><?= h($loan->user->url) ?></a></td>
                </tr>
                <tr class="row mx-0">
                    <th class="col-3"><?= __('所在地') ?></th>
                    <td class="col-9"><?= h($loan->user->company_address1) ?></td>
                </tr>
                <tr class="row mx-0">
                    <th class="col-3"><?= __('設立年月日') ?></th>
                    <td class="col-9"><?= h($loan->user->established_in) ?></td>
                </tr>
                <tr class="row mx-0">
                    <th class="col-3"><?= __('社員数') ?></th>
                    <td class="col-9"><?= h($loan->user->staff_count).' 人' ?></td>
                </tr>
                <tr class="row mx-0">
                    <th class="col-3 bottom"><?= __('担当者名') ?></th>
                    <td class="col-9 bottom"><?= h($loan->user->last_name." ".$loan->user->first_name." (".$loan->user->last_name_kana." ".$loan->user->first_name_kana.")") ?></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="loan-info mt-5">
        <div class="contents-semi-label">
            <?= __('案件詳細') ?>
        </div>
        <div class="contents">
            <table>
                <tbody>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('案件名') ?></th>
                        <td class="col-9"><?= h($loan->loan_title) ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('希望融資額') ?></th>
                        <td class="col-3 left"><?= number_format(h($loan->desired_loan_amount)).' 円' ?></td>
                        <th class="col-2"><?= __('希望融資期間') ?></th>
                        <td class="col-4"><?= h($loan->loan_period).' ヶ月' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('資金使途') ?></th>
                        <?php if ($loan->loan_purpose == 2) { ?>
                            <td class="col-9"><?= nl2br($loan->loan_purpose_detail) ?></td>
                        <?php } else { ?>
                            <td class="col-9"><?= h($loan->loan_purpose_view) ?></td>
                        <?php } ?>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('業種') ?></th>
                        <td class="col-9"><?= h($loan->category->name."  >  ".$loan->sub_category->name) ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('事業内容') ?></th>
                        <td class="col-9"><?= nl2br(h($loan->job_description)) ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 bottom"><?= __('追加コメント') ?></th>
                        <td class="col-9 bottom"><?= nl2br(h($loan->prospect)) ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="finance-info mt-5">
        <div class="contents-semi-label">
            <?= __('財務情報') ?>
        </div>
        <div class="contents">
            <table>
                <tbody>
                    <tr class="row mx-0">
                        <th class="col-3"><?= __('総資産') ?></th>
                        <td class="col-3 left"><?= number_format(h($finance->assets)).' 円' ?></td>
                        <th class="col-2"><?= __('融資残高') ?></th>
                        <td class="col-4"><?= number_format(h($finance->loan_balance)).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-12"><?= h(array_keys($finance->revenues)[0]).'年'.h($finance->financial_month).'月期' ?></th>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5">売上</th>
                        <td class="col-9"><?= h($finance->revenues[array_keys($finance->revenues)[0]]).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5">損益</th>
                        <td class="col-9"><?= h($finance->profits_losses[array_keys($finance->profits_losses)[0]]).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-12"><?= h(array_keys($finance->revenues)[1]).'年'.h($finance->financial_month).'月期' ?></th>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5">売上</th>
                        <td class="col-9"><?= h($finance->revenues[array_keys($finance->revenues)[1]]).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5">損益</th>
                        <td class="col-9"><?= h($finance->profits_losses[array_keys($finance->profits_losses)[1]]).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-12"><?= h(array_keys($finance->revenues)[2]).'年'.h($finance->financial_month).'月期' ?></th>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5">売上</th>
                        <td class="col-9"><?= h($finance->revenues[array_keys($finance->revenues)[2]]).' 円' ?></td>
                    </tr>
                    <tr class="row mx-0">
                        <th class="col-3 pl-5 bottom">損益</th>
                        <td class="col-9 bottom"><?= h($finance->profits_losses[array_keys($finance->profits_losses)[2]]).' 円' ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-6 text-right pr-5">
            <?php
                if ($loan->is_favorited) {
                    echo $this->Form->button(__('お気に入り登録解除'), ['type' => 'button', 'id' => 'fav_btn', 'class' => 'button button-md']);
                } else {
                    echo $this->Form->button(__('お気に入り登録'), ['type' => 'button', 'id' => 'fav_btn', 'class' => 'button button-md']);
                }
            ?>
        </div>
        <div class="col-6 text-left pl-5">
            <?php echo $this->Form->button(__('コンタクト開始'), ['class' => 'button button-md']); ?>
        </div>
    </div>
</div>